apiVersion: v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
    spec:
      containers:
       —name: java
          image: java-app 
          ports:
           —containerPort: 80
